name: Deploying site

on:
  push:
    branches:
      - develop

env:
  NODE_VERSION: '18.x'       

jobs:
  build:
    name: install, build, test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1      
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      id: install
      run: yarn install
    # Build
    - name: Build
      id: build
      run: yarn build
    # Test
    #- name: Test
    #  id: test
    #  run: yarn test
    - name: Deploying
      id: deploy
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER_2 }}
        password: ${{ secrets.FTP_PASSWORD_2 }}
        username: ${{ secrets.FTP_USERNAME_2 }}
        local-dir: dist/
        server-dir: ${{ secrets.REMOTE_DIR_2 }}