name: Deploying site

on:
  push:
    branches:
      - develop

env:
  NODE_VERSION: '10.x'       

jobs:
  build:
    name: install, build, test and deploy site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1      
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      id: install
      run: yarn install
    # Build
    - name: Build
      id: build
      run: yarn build
    # Test
    - name: Test
      id: test
      run: yarn test
    # Deploy
    - name: Deploy
      id: deploy
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
       FTP_SERVER: ${{ secrets.FTP_SERVER }}
       FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
       FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
       LOCAL_DIR: dist
       REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
